### ISSUE TITLE
编辑器字体

### ISSUE THREAD

**Issue by wangsizhu0504** [xlboy/ts-type-hidden#1]
这个编辑器用的什么字体，好漂亮 ~~~

<img width="1422" alt="233914174-a536689e-cd80-4d87-81d4-104160be7c5e" src="https://user-images.githubusercontent.com/39726513/234778026-501dbd6c-260a-42e4-b065-5cd354d07b2a.png">

**Comment by xlboy** [comment]
是系统内置的 `ComicSansMS`（不论 windows/mac）

**Comment by wangsizhu0504** [comment]
> 是 `ComicSansMS`，是系统内置的（不论 windows/mac）

👍太棒了
