### ISSUE TITLE
Not hidding generics in Class definitions 

### ISSUE THREAD

**Issue by fsgreco** [xlboy/ts-type-hidden#11]
Seems like there is a little bug that do not hide the generics definition when creating a Class (it does it well when it's a function definition).  

I'm attaching an image for better understanding: 
![image](https://github.com/user-attachments/assets/9820faae-3dc4-4a1b-a0f1-a46dcc636457)

**Comment by xlboy** [comment]
Thank you for your feedback. I will address this issue and release an update in the next few days.

**Comment by xlboy** [comment]
The issue has been fixed and released in the latest version.

**Comment by fsgreco** [comment]
Thank you very much, it works fine! (just tested it)
