### ISSUE TITLE
Also Fold when hide

### ISSUE THREAD

**Issue by mefengl** [xlboy/ts-type-hidden#2]
![image](https://github.com/xlboy/ts-type-hidden/assets/71683364/d3c28908-016b-49b8-ac03-b99474c5705e)

如果能把这几行代码合并成一行，就不会有那么多空白了

**Comment by xlboy** [comment]
像这几行是由 `多句类型` 组成的吗，例：

```ts
type A = 1;
type B = 2;
type C = 3;
```
---
如果是这种 `多句类型` 的话，的确不会折叠成1行（之前思考过这个点，怕产生需求冲突，所以先放着了）

**Comment by mefengl** [comment]
像这样的
![image](https://github.com/xlboy/ts-type-hidden/assets/71683364/6df3fd04-2062-4d40-bdf8-db1290005d25)

**Comment by mefengl** [comment]
像这样的
![image](https://github.com/xlboy/ts-type-hidden/assets/71683364/aeac3ed7-b4ff-4c5e-b780-40fe4e2f9035)

**Comment by xlboy** [comment]
> 像这样的 ![image](https://user-images.githubusercontent.com/71683364/239510231-aeac3ed7-b4ff-4c5e-b780-40fe4e2f9035.png)

喔，如果是这样的话，按理说是会折叠的！

你可以尝试一下触发一下 `ts-type-hidden.toggle` 的命令来刷新一下，看看它会不会折叠成 1 行

---

示例：

[示例](https://github.com/xlboy/ts-type-hidden/assets/63690944/bac1d54a-5c56-45b6-b200-29e32261bd93)

**Comment by mefengl** [comment]
没错，重启后就会折叠了~
