### ISSUE TITLE
功能需求：增加是否显示 `type` 或 `interface` 定义的类型的配置项

### ISSUE THREAD

**Issue by kahosan** [xlboy/ts-type-hidden#5]
目前在光标离开 `type` 或 `interface` 定义的那行时，就会默认隐藏掉，能不能增加一个配置来控制它？
这个配置应当只影响下述示例，而不会对函数参数，变量等有影响

```ts
type A = string;
interface B = { a: string };
```

**Comment by xlboy** [comment]
> 目前在光标离开 `type` 或 `interface` 定义的那行时，就会默认隐藏掉，能不能增加一个配置来控制它？ 这个配置应当只影响下述示例，而不会对函数参数，变量等有影响
> 
> ```ts
> type A = string;
> interface B = { a: string };
> ```
喔，我之前也有过关于这块的想法，但后面我还是选择了：**人们需要对类型进行操作时，则全部展开。不需要做操作时，则全部隐藏**（即，操作完这一两行类型后，再触发快捷键将其及其他一起隐藏起来）

**Comment by xlboy** [comment]
> 



> > 目前在光标离开 `type` 或 `interface` 定义的那行时，就会默认隐藏掉，能不能增加一个配置来控制它？ 这个配置应当只影响下述示例，而不会对函数参数，变量等有影响
> > ```ts
> > type A = string;
> > interface B = { a: string };
> > ```
> 
> 喔，我之前也有过关于这块的想法，但后面我还是选择了：**人们需要对类型进行操作时，则全部展开。不需要做操作时，则全部隐藏**（即，操作完这一两行类型后，再触发快捷键将其及其他一起隐藏起来）

但现在再仔细一想，人们可能就是临时需要看到这一两行重要内容（边写逻辑代码，边看这一两行具有辅助意义的类型代码），事后就可以忽略不计了

这么一看，或许它的确有一定的价值！

---

从实现层面的话，我想的是通过快捷键将当前光标所在的 **类型块域** 进行收集起来，这样在光标离开 `type` 或 `interface` 时可以根据收集到的 类型块域信息 来做**隐藏过滤**

**Comment by kahosan** [comment]
感觉没有必要实现的那么细节
快捷键一般都是临时使用开启或关闭，作用到全局与作用到某个块级或某个文件内实际用起来应该是没有区别的

然后从使用角度上：我想它（类型定义）可以默认是隐藏状态，通过快捷键临时切换为显示或通过配置项永久切换为显示

**Comment by xlboy** [comment]
> 感觉没有必要实现的那么细节 快捷键一般都是临时使用开启或关闭，作用到全局与作用到某个块级或某个文件内实际用起来应该是没有区别的
> 
> 然后从使用角度上：我想它（类型定义）可以默认是隐藏状态，通过快捷键临时切换为显示或通过配置项永久切换为显示

听着感觉大概是——**“隐藏时要忽略的类型种类”**（interface, type-alias, type-parameter, ...）

关于这块相关的我得想想

**Comment by kahosan** [comment]
是的，你说得比较准确。也可以是 **隐藏指定的类型种类**
有什么需要我帮忙欢迎提出

**Comment by xlboy** [comment]
可以了！迟来的实现…
相关配置项为： `ts-type-hidden.ignoreTypeKinds`，具体的填参可以根据配置时的智能感应得知

**演示视频：**

https://github.com/xlboy/ts-type-hidden/assets/63690944/f893f9e1-7fb4-4356-b76a-0d33fde9fc20

---
**预览版的 `vsix` 安装包**（解压出来后即可看到纯正的 `vsix` 安装包）：
[ts-type-hidden-0.4.0-dev.2.vsix.zip](https://github.com/xlboy/ts-type-hidden/files/12388620/ts-type-hidden-0.4.0-dev.2.vsix.zip)

> ***PS：*** 先把原来的 `v0.3.0` 卸载，然后再 **从 VSIX 中安装**，如图：↓ 
> 
> <img width="712" alt="image" src="https://github.com/xlboy/ts-type-hidden/assets/63690944/338fc14a-22ee-46d7-8efe-df9fa63c34e6">

---

如果你还感兴趣的话可以试试…我计划是在下周二将此功能带到 `v0.4.0` 中，这期间有什么问题都可以在这交流~

**Comment by kahosan** [comment]
非常感谢，看起来很符合需求，我会在此期间进行试用
如果此 issue 没有更新，`v0.4.0` 发布后可直接关闭此 issue

**Comment by xlboy** [comment]
OK 咯，配置项这边的命名有些小改变。感谢你对插件的支持~ 💐
