### ISSUE TITLE
功能需求：希望加入复制隐藏type后的js代码

### ISSUE THREAD

**Issue by HaibaraAiAPTX** [xlboy/ts-type-hidden#6]
需求场景：某些时候，我们在借鉴别人代码的时候会clone下来，但是这个时候我们没有安装依赖，如果只想简单的跑某一个函数查看逻辑，则需要复制这个函数到js runtime里面跑，浏览器或者其他工具，但一般情况下这个函数是ts写的，但是隐藏type后复制到的代码依然是带有type的ts代码，所以希望加入此功能。

**Comment by xlboy** [comment]
想了一下，觉得还是超出了插件的定位，这类功能还是建议用回原本的方式吧
